### ISSUE TITLE
(git master) crash at QuickNote/ToDo selection setting

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1860]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

I can setup the notes folder, this works fine.
Normaly I don't change the Quicknote file, because it is located fine in the notes folder.

But I always change the todo file, which is located in a subfolder: todo

I do this not so often, because I try to use backups of settings. On the Mordor I don't want to use a backup but I want to keep as much as possible default.

It is not possible to change the todo file. First time when I tried I could select the folder and the file. But this did not select the file for settings, but opened it.
And starting with next attempt to set the file, Mordor crashes. always.
The same happens when I try to change quicknote location

### Steps to reproduce

1. 
2. 
3. 

### Information

Android version: 12
Device: Poco M4 Pro
App Version: 
would be fine to allow copy and paste from the settings. Something like a hint (and implementation)
"Long press to copy version (and maybe other required information - Android version, device and so on)", 
instead of manually entering it here

It is a very long version. suffix (220923)

### Source

git master branch

### Format / File type

Not specific

### Additional info / Log

```shell


java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase(java.util.Locale)' on a null object reference
at net.gsantner.opoc.util.GsContextUtils.getMimeType(GsContextUtils.java:988)
at net.gsantner.opoc.util.GsContextUtils.getMimeType(GsContextUtils.java:963)
at net.gsantner.markor.frontend.filebrowser.MarkorFileBrowserFactory.lambda$static$0(MarkorFileBrowserFactory.java:29)
at net.gsantner.markor.frontend.filebrowser.MarkorFileBrowserFactory$$ExternalSyntheticLambda0.callback(Unknown Source:4)
at net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter.accept(GsFileBrowserListAdapter.java:598)
at java.io.File.listFiles(File.java:1259)
at net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter$1.run(GsFileBrowserListAdapter.java:483)

```

**Comment by aisbergde** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase(java.util.Locale)' on a null object reference
	at net.gsantner.opoc.util.GsContextUtils.getMimeType(GsContextUtils.java:988)
	at net.gsantner.opoc.util.GsContextUtils.getMimeType(GsContextUtils.java:963)
	at net.gsantner.markor.frontend.filebrowser.MarkorFileBrowserFactory.lambda$static$0(MarkorFileBrowserFactory.java:29)
	at net.gsantner.markor.frontend.filebrowser.MarkorFileBrowserFactory$$ExternalSyntheticLambda0.callback(Unknown Source:4)
	at net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter.accept(GsFileBrowserListAdapter.java:598)
	at java.io.File.listFiles(File.java:1259)
	at net.gsantner.opoc.frontend.filebrowser.GsFileBrowserListAdapter$1.run(GsFileBrowserListAdapter.java:483)

**Comment by aisbergde** [comment]
the latest f-droid version doesn't crash, but works fine.

**Comment by harshad1** [comment]
I think this issue is fixed in https://github.com/gsantner/markor/pull/1839

**Comment by gsantner** [comment]
>  would be fine to allow copy and paste from the settings. Something like a hint (and implementation)

When you press the field where this version is written and it's copied to clipboard.

> MimeType

Hidden that for now, that discussion seems to be at 3 places now.

**Comment by aisbergde** [comment]
if I short or lang press the field containing the version, then always the Markor website opens. nothing will be copied into clipboard. Maybe this depends on the operation system. I use MIUI

**Comment by gsantner** [comment]
![screenshot-2022-09-28__21-18-18](https://user-images.githubusercontent.com/6735650/192869831-9a6b41d8-3c86-4f1d-baf3-c106a3985cc4.png)

**Comment by aisbergde** [comment]
OK, I got it. I tried on top of the about section, where I can read the version.
Next time I will copy build information.

If there will be a next time. Because I feel, my feedback is qualified as disturbing and unqualified.

**Comment by gsantner** [comment]
Ah I didn't know you were referring only to the top section.
