### ISSUE TITLE
Wish makor make option to remove or not the empty line in .todo.txt when sorting

### ISSUE THREAD

**Issue by ccchan234** [gsantner/markor#1943]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. Markor should not remove the EMPTY line in xxx.todo.txt, please

Using Markor with obsidian is the way to go, obs is like an add-on that a text editor like markor cant provide: hyperlinks, "engines/commands" like dataview, calendar etc. But when I just want a fast, straight edit, i'll use markor.

HOWEVER, for .todo.txt, obsidian need it renamed .todo.md;

besides, in makor, when you sort .todo.? files, the entries are really re-arranged in the .todo.? files (simpletask didn't).

Reason to keep the empty line:

obsidian needs at least an empty line above AND below the entry to treat it as a "block", in this way you can hyperlink exactly to this block.

e.g. in test.todo.md

task1 xxx xxx
task 2 xxx xxx
test 3 xxx xxx

then I cant hyperlink to task2, because obsidian will treat all 3 as a paragraph.

but if the file stays: (I have to manually add the empty line if use markor /w .todo.md)

task1 xxx xxx
(empty line)
task 2 xxx xxx
(empty line)
test 3 xxx xxx

then obsidian will know task 2 is a "block" and can hyperlink EXACTLY to this entry, which is superior.

my current solution is to use simpletask to co-operate with obsidian for todo.? files (obsidian can only handle todo.md as markdown files, cant sort them in contrast to markor/simpletask)

Markdown is good as editor on it's own, even good as a todo.txt editor;
but it will be even better if somehow it can blend in with obsidian.

ps: hard to ask obsidian to modify the "block" recognition issue i think, as it is sense to use empty lines to differ lines from "blocks".

thanks

### Information

Android version: 12
Device: a33-5g
App Version:  lastest

### Source

F-Droid

### Format / File type

todo.txt

**Comment by ccchan234** [comment]
better keep only 1 single empty line at most however, thx

**Comment by gsantner** [comment]
Can you please clarify if it really is about todo.txt format or markdown format now? You said that you renamed the file from todo.txt to some .md, telling me you want to go the Markdown direction. 

> my current solution is to use simpletask

SimpleTask is todo.txt-only software.

> to co-operate with obsidian for todo.

I don't use obsidian, but to my knowledge the focus is only on Markdown - not todo.txt.

So to my understanding, you need to strike one/replace one from the equitation, if you want to use the same file everywhere.

**Comment by gsantner** [comment]
Can you please clarify if it really is about todo.txt format or markdown format now? You said that you renamed the file from todo.txt to some .md, telling me you want to go the Markdown direction. 

> my current solution is to use simpletask

SimpleTask is todo.txt-only software.

> to co-operate with obsidian for todo.

I don't use obsidian, but to my knowledge the focus is only on Markdown - not todo.txt.

So to my understanding, you need to strike one/replace one from the equitation to get proper working support/buttons/highlighting etc, if you want to use the same file everywhere.

> Markdown is good as editor on it's own, even good as a todo.txt editor;
> but it will be even better if somehow it can blend in with obsidian.

To my understanding, obsidian not having todo.txt support is your main problem / what you want. Not sounds like this is something that requires changes at Markor.

**Comment by ccchan234** [comment]
hi,

for a file that contain ASCII, that could be some.todo.txt OR some.todo.md, let's make it some.todo.md for simple.

At first it looks like this:

![image](https://user-images.githubusercontent.com/37549409/210108328-234c5273-5d2a-48ae-8ba1-eb54f6b7bef7.png)

i can manipulate it using simpletask:

![image](https://user-images.githubusercontent.com/37549409/210108426-906022cd-7a9a-4d13-8db2-32d0351c4636.png)

you notice that then entry1, 2, 3, 4 are not moving even i sorted them in the app, simpletask simply add the priority, uuid etc into the entries and didn't remove empty lines, didn't sort the entries indeep!

if raw-02.todo.md is opened as .todo.md in markor and force it in .todo.txt mode.
markor opened it fine.

but after a sort of priority USING markor, it becomes:
![image](https://user-images.githubusercontent.com/37549409/210108587-d37c7d0e-071c-45c2-be66-210b3c9b6855.png)

obviously it disturbed the structure of "empty line, entry line, empty line, entry line".

I understand markor DID modify the .todo.md in a way that the sorting is written to the file.
I/obsidian dont care on the sorting or not, but the REMOVAL of EMPTY LINES destroyed the structure, which is also a "data".

It will be good if markor could add a toggle and let us choose whether empty lines are removed or not when files are re-written, but it's still fine if not as FOSS is in that way.

anyway thanks for markor, for direct markdown editing markor is still prefered than other editors.

thanks

**Comment by ccchan234** [comment]
hi, just realize that the empty lines are NOT removed in markor but got sorted into the bottom!

in that way it's hard for markor to be compatible with obsidian to manipulate the .todo.md/txt files.

i think i have to turn to simpletask for .todo.md;

still use markor for simple direct .md edition, and use obsidian over the .md files for hyperlinkings.

thanks for the time.
