### ISSUE TITLE
todo.txt - if a task contains a link the link is not displayed in search

### ISSUE THREAD

**Issue by naunan** [gsantner/markor#1961]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When having a task with a link, it is possible to search for it but the link will not be displayed in the results. Other text in the same task, + and @ will be displayed.

![2023-01-26 08 19 44](https://user-images.githubusercontent.com/110349879/214778543-8b69ea8a-d17b-4b2c-96dd-51d4c871c10e.jpg)

### Steps to reproduce

1. Create task which includes a link
2. search for the task via the search function 

### Information

Android version: 13
Device: Pixel 5
App Version: 2.10.7 (143)

### Source

F-Droid

### Format / File type

todo.txt

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Interesting, I add links to my todo.txt file from time to time but would not have ever noticed.
