### ISSUE TITLE
Safety copy, bavkup notebook/QuickNote/To-Do

### ISSUE THREAD

**Issue by sunvis0r** [gsantner/markor#1963]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Due to autosave, Markor saved QuickNote.md with partially erased information (to a month ago). Whether this was a bug on the part of Markor, or whether the keyboard is to blame, I don’t know, because I don’t know the steps to repeat it (I just entered the information, pressed the save button and exited the application). It would be great if Markor could make backups - to prevent the consequences of bugs or accidental user errors

### Information

Android version: 12
Device: POCO F3
App Version: 2.10.6

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Markor saves plain old text files to disk. Most users use another app to backup.

**Comment by sunvis0r** [comment]
This can be done like in Notepad++: autosave saves only backup file, but the Save button works for the main file (and the red icon that the document is not saved). Autosave will continue to work, but more safely

**Comment by gsantner** [comment]
This topic was previously discussed at #954 / seemingly duplicate.
